---
title: "Examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Examples}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
--- 

There are currently 3 full examples contained withing the `inst` directory within the package: 

## Example: `add_twitter_card()` for Rmd knitted documents

Within `inst -> examples`, there is an Rmd document called `twitter_large.Rmd`.  When knitted, this document creates a html page containing twitter meta tags that we have stored on `www.jumpingrivers.com`. The code use to create the meta tags is also in the document. To preview the twitter card for this document, copy and paste the page URL into the [twitter card validator](https://cards-dev.twitter.com/validator). 

## Example: `add_og_card()` for Rmd knitted documents

Again, within `inst -> examples`, there is an Rmd document, this time called `open_graph.Rmd`. When knitted, this document creates a html page containing open graph meta tags that we have stored on `www.jumpingrivers.com`. The Rmd document also contains the code to create the meta tags in the header. I have found the best way to preview open graph sharing cards is to download the chrome extension [Open Graph Preview](https://chrome.google.com/webstore/detail/open-graph-preview/ehaigphokkgebnmdiicabhjhddkaekgh/related).

## Example: `add_twitter_card()` for Rmd knitted slides

Within `inst -> examples`, there is an Rmd document, this time called `twitter_slides.Rmd`. When knitted, this produces html slides. Again, using the same technique, we can add meta tags into the header of the document. This time we've added the same meta tags as the first `add_twitter_card()` example (about bees). We have also stored these slides on `www.jumpingrivers.com`. To preview the twitter card copy and paste the URL into the [twitter card validator.](https://cards-dev.twitter.com/validator)
